"""empty message

Revision ID: 0dd05b57c699
Revises: bec3fc208377
Create Date: 2018-03-05 01:33:02.119548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd05b57c699'
down_revision = 'bec3fc208377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notification', sa.Column('transaction_icon_id', sa.String(), nullable=True))
    op.drop_constraint(u'Notification_transaction_icon_fkey', 'Notification', type_='foreignkey')
    op.create_foreign_key(None, 'Notification', 'Icon', ['transaction_icon_id'], ['id'])
    op.drop_column('Notification', 'transaction_icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notification', sa.Column('transaction_icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Notification', type_='foreignkey')
    op.create_foreign_key(u'Notification_transaction_icon_fkey', 'Notification', 'Icon', ['transaction_icon'], ['id'])
    op.drop_column('Notification', 'transaction_icon_id')
    # ### end Alembic commands ###
