"""empty message

Revision ID: 3a5da93838c6
Revises: a61d53ffb9c3
Create Date: 2018-02-22 15:37:54.447610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5da93838c6'
down_revision = 'a61d53ffb9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Wallet', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('Wallet', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Wallet', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Wallet', 'description')
    # ### end Alembic commands ###
