"""empty message

Revision ID: 805d928ccd53
Revises: 3a5da93838c6
Create Date: 2018-03-04 16:34:24.729625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805d928ccd53'
down_revision = '3a5da93838c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdmissionType',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admission_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_type'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('FreeRide',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('rides_had', sa.Integer(), nullable=True),
    sa.Column('token_status', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('SchoolInfo',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('DriverInfo',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('car_model', sa.String(), nullable=True),
    sa.Column('left_image', sa.String(), nullable=True),
    sa.Column('right_image', sa.String(), nullable=True),
    sa.Column('front_image', sa.String(), nullable=True),
    sa.Column('back_image', sa.String(), nullable=True),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('admin_confirmed', sa.Boolean(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('admission_type_id', sa.String(), nullable=True),
    sa.Column('number_of_rides', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admission_type_id'], ['AdmissionType.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    op.add_column(u'User', sa.Column('mobile_number', sa.String(), nullable=True))
    op.add_column(u'User', sa.Column('number_of_rides', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'User', 'number_of_rides')
    op.drop_column(u'User', 'mobile_number')
    op.drop_table('DriverInfo')
    op.drop_table('SchoolInfo')
    op.drop_table('FreeRide')
    op.drop_table('AdmissionType')
    # ### end Alembic commands ###
