"""empty message

Revision ID: a61d53ffb9c3
Revises: 
Create Date: 2018-02-22 15:09:36.741165

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = 'a61d53ffb9c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PercentagePrice',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('UserType',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_type_id', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('authorization_code', sa.String(), nullable=True),
    sa.Column('authorization_code_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['UserType.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_code'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Notification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('recipient_id', sa.String(), nullable=True),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Wallet',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wallet_amount', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_detail', sa.String(), nullable=False),
    sa.Column('type_of_operation', ENUM('wallet_type', 'ride_type', 'transfer_type', name='operationtype', create_type=False), nullable=False),
    sa.Column('type_of_transaction', ENUM('credit_type', 'debit_type', 'both_types', name='transactiontype', create_type=False), nullable=False),
    sa.Column('cost_of_transaction', sa.Float(), nullable=True),
    sa.Column('receiver_amount_before_transaction', sa.Float(), nullable=True),
    sa.Column('receiver_amount_after_transaction', sa.Float(), nullable=True),
    sa.Column('sender_amount_before_transaction', sa.Float(), nullable=True),
    sa.Column('sender_amount_after_transaction', sa.Float(), nullable=True),
    sa.Column('paystack_deduction', sa.Float(), nullable=True),
    sa.Column('receiver_id', sa.String(), nullable=True),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('receiver_wallet_id', sa.String(), nullable=True),
    sa.Column('sender_wallet_id', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['receiver_wallet_id'], ['Wallet.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['Wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transaction')
    op.drop_table('Wallet')
    op.drop_table('Notification')
    op.drop_table('User')
    op.drop_table('UserType')
    op.drop_table('PercentagePrice')
    # ### end Alembic commands ###
