"""empty message

Revision ID: bec3fc208377
Revises: 805d928ccd53
Create Date: 2018-03-05 01:12:25.081354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec3fc208377'
down_revision = '805d928ccd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Icon',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_type')
    )
    op.add_column(u'Notification', sa.Column('transaction_icon', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Notification', 'Icon', ['transaction_icon'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Notification', type_='foreignkey')
    op.drop_column(u'Notification', 'transaction_icon')
    op.drop_table('Icon')
    # ### end Alembic commands ###
